### ISSUE TITLE
Is a CocoaPod version planned?

### ISSUE THREAD

**Issue by tscholze** [dunkelstern/twohundred#1]
It would be great to use twohundred as a CocoaPod. It would simplify the updating process and it would stop people to use Git submodules - a devil's invention.

Thanks for your great work.
- Toby

**Comment by dunkelstern** [comment]
Currently my focus is on getting it to work on Linux, Cocoapods may follow but because of the many small packages the Swift package manager dictates I will not commit the Podspec files to the official Cocoapods repo to not spam my packages there.

**Comment by tscholze** [comment]
Okay, thanks for your feedback. In my opinion, we could close this issue. I'm looking forward to hear more from two hundred or it's child projects.
